version: 2

# Keep this at the top to prevent notifications when config.yml is invalid
experimental:
  notify:
    branches:
      only:
        - master

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO_TOOL_PACKAGES: >
            github.com/jstemmer/go-junit-report
          TEST_RESULTS: /tmp/test-results
          GOFLAGS: -mod=vendor
    steps:
      - checkout
      - run: go install $GO_TOOL_PACKAGES
      # We have to install python to use pre-commit :(
      - run: sudo apt-get install python-pip
      - run: sudo pip install pre-commit
      - run: make init
      - run: pre-commit run -a
      - run:
          name: Verify that packr files are committed
          command: make packr && git status --porcelain
      - run: go build ./...
      - run: mkdir -p ${TEST_RESULTS}
      - run: |
          trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
          go test -v -race ./...| tee ${TEST_RESULTS}/go-test.out 2>&1
      - store_test_results:
          path: /tmp/test-results

